flags: {}
packages:
- '.'
- '../brisk'
compiler-check: newer-minor
resolver: lts-8.3
extra-deps:
  - distributed-process-0.6.6
  - distributed-process-client-server-0.1.3.2
  - dynamic-loader-0.0.1
  - distributed-process-async-0.2.3
  - distributed-process-extras-0.2.1.2
